### ISSUE TITLE
Construct Configuration tree

### ISSUE THREAD

**Issue by henrym2** [GoogleChromeLabs/IseWebSecurityBundle#4]
In order to provide a complete development experience when using the bundle, a robust configuration is required. The config tree should allow a developer to control the majority of the moving parts in the bundle, or to use a fire and forget preset that will handle the majority of the configuration for them.

The configuration should consist of two primary parts, **Default/Global** and **Paths**. Both will share the same attributes, however any specified configuration in the **Paths** space, will overwrite the **Default** configuration in that case. An example configuration is as follows:

```yaml
ise_web_security:
  default:
    preset: full
    fetch_metadata: 
      allowed_endpoints: ['/images', '/api/health'] 
  paths:
    '^/api': 
        report_uri: "https://localhost:3000/report"
        coop:       cross-site
        coep:       report-only
    '/index':
        report_uri: "https://report-uri:3000/report"
        coop:       cross-site
        coep:       report-only
    '/admin':
        preset: full
```
The full structure of the config is subject to some change. Discussions around it should be kept in this Issue ticket for future documentation
